spring:
  application:
    name: learn-feign
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

hystrix:
  command:
    default: #default全局有效，service id指定应用有效 
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据 
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

ribbon:
  ReadTimeout: 3000
  ConntectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false #是否所有操作都重试
